version: "3.8"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile

    image: nodejs
    ports:
      - "3000:3000"
    volumes:
      - ../:/usr/src/app
    command: bash -c "npm install && npm start"

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../storage/dbdata:/var/lib/mysql
      - ../database.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - 3307:3306
